plugins {
    id 'org.springframework.boot' version '2.7.18'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
    id 'java'
}

group = 'com.mall'
version = '1.0.0'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
    implementation 'com.alibaba:druid-spring-boot-starter:1.2.16'
    runtimeOnly 'com.mysql:mysql-connector-j'
    compileOnly 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    
    // Apache POI for Excel export
    implementation 'org.apache.poi:poi-ooxml:4.1.2'
    
    // Commons FileUpload
    implementation 'commons-fileupload:commons-fileupload:1.4'
    implementation 'commons-io:commons-io:2.11.0'
    
    // JWT
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    mainClass = 'com.mall.MallApplication'
}